### ISSUE TITLE
apollo.config.js + apollo service:download throws when localSchemaFile is missing

### ISSUE THREAD

**Issue by sseppola** [apollographql/apollo-tooling#1255]
**Intended outcome:**
With `apollo.config.js` defined, download new schema for use with `apollo client:codegen`
```apollo service:download --endpoint ${GQL_URI:='http://localhost:3131/graphql'} ../graphql.schema.json
```

**Actual outcome:**
It throws an error because it fails to read the schema file that it is supposed to download itself..
![Screen Shot 2019-05-10 at 18 42 47](https://user-images.githubusercontent.com/4065840/57544205-f1a4c580-7356-11e9-8e77-82c9cc3229f0.png)

**How to reproduce the issue:**
Create an `apollo.config.js` file configured with `localSchemaFile` and ensure the referenced local schema does not exist.

**Versions**
"apollo": "2.6.2"

**Related**
https://github.com/apollographql/apollo-tooling/issues/1107
https://github.com/apollographql/apollo-tooling/issues/792

**Edit**
Also tested with `apollo@2.11.0`

**Comment by sseppola** [comment]
This may be something else, but as I try to share my schema file in a monorepo with the following structure:
```
apollo.config.js
app
    package.json
    src
web
    package.json
    src
```

With apollo.config.js:
```js
module.exports = {
  client: {
    includes: ['./web/src/**/*.graphql', './app/src/**/*.graphql'],
    service: {
      name: 'mingl-app-schema',
      localSchemaFile: __dirname + '/graphql.schema.json',
    },
  },
};
```

When I run `apollo service:download --endpoint ${GQL_URI:='http://localhost:3131/graphql'} ../graphql.schema.json` in the web directory apollo:
- (to my surprise) found the config file in the parent directory
- runs `localSchemaFile` path defined in the config file relative to web (fixed by prepending `__dirname` as shown above)

When generating types with `apollo client:codegen --addTypename --outputFlat --localSchemaFile ../graphql.schema.json --target typescript --includes 'src/**/*.graphql' ./src/__generated/apollogen-types.ts` it seems to rely on the latest string in the `includes` array, when in reality I want the cli parameter to specify. Removing `includes` from apollo.config.js just results in an error:
```
⚠️  It looks like there are 0 files associated with this Apollo Project. This may be because you don't have any files yet, or your includes/excludes fields are configured incorrectly, and Apollo can't find your files. For help configuring Apollo projects, see this guide: https://bit.ly/2ByILPj
  ✔ Loading Apollo Project
  ✖ Generating query files with 'typescript' target
    → No operations or fragments found to generate code for.
```

😓

**Comment by JakeDawkins** [comment]
Hi @sseppola! Thanks for opening this issue. It touches on a couple quirks that are mostly documentation/educational issues we haven't quite figured out yet.

The biggest one is the idea of a `service` vs `client` config. `client` configs are ones with a top-level `client` key in the config (like yours). **When you're using a client config, you can only run `client:*` commands**. So `service:download` isn't _designed_ to work here, as it's looking for a top-level `service` key in the config (although the error messages related aren't helpful at all).

We just released a `client:download-schema` [command](https://github.com/apollographql/apollo-tooling#apollo-clientdownload-schema-output) in the latest release of the CLI that should work just fine for you.

> This may be something else, but as I try to share my schema file in a monorepo with the following structure

The apollo config format is only really _designed_ to work with a single project. So ideally, you'd have 2 config files; one for each project. Since they're both client projects and seem to share schemas, just adding 2 globs in the `includes` (like you were doing) should work fine for you.

> It looks like there are 0 files associated with this Apollo Project

This shows up when the `includes` globs don't match any files. If you use the default value for `includes` or don't manually specify one, it will look under `./src/` for files (which is why you saw that error).

> (to my surprise) found the config file in the parent directory

We use a tool called cosmiconfig to load configs right now, and its default behavior is look _up_ a file tree to find config files if one isn't found in the directory you're running it in (yeah, that's a bit weird).

I hope this is helpful! Since I don't _think_ this is a technical issue, I'll close this, but I'm happy to reopen/answer any other questions if you have any :) Sorry for the trouble!

**Comment by sseppola** [comment]
Thanks for the reply @JakeDawkins.

I switched to `client:download-schema`, and I'm now running only `client:` commands and I have not changed my config other than that.

However I continue to have a problems, I'll try to be a bit more specific than above:

### 1. Generating schema
I still cannot run `client:download-schema` without the local schema already in place. It's possible to work around, but feels like an unnecessary problem to have. It will mostly affect A) new projects 2) environments where you want to just download the newest schema from the api every time.

### 2. Generating types
I get different results if I use:
```json
includes: ['./app/src/**/*.graphql', './web/src/**/*.graphql'],
```
vs
```json
includes: ['./web/src/**/*.graphql', './app/src/**/*.graphql'],
```

Running `apollo client:codegen --addTypename --passthroughCustomScalars --customScalarsPrefix GQL_ --outputFlat --localSchemaFile ../graphql.schema.json --target typescript --includes 'src/**/*.graphql' src/__generated/apollogen-types.ts` from the `web` directory with the latter `includes` config I end up missing lots of types specific to web. So it seems to have some preference to the latter glob.

### 3. Inflexible command config
Honestly I only use `apollo.config.js` to enable `vscode-apollo` integration, which needs to know about my schema file. That's the only reason I added this config file, everything was working perfectly before (even using the `service:download` command).

My ideal config is to provide no `includes` and just provide it directly in the CLI, so what I really want is for `apollo.config.js` to be used only as a way to fetch default arguments, which would've solved all of my problems.
