### ISSUE TITLE
Apollo GraphQL not appearing in VSCode output view dropdown

### ISSUE THREAD

**Issue by jsonunger** [apollographql/apollo-tooling#664]
Was excited to start using the new `Apollo GraphQL` VSCode extension, but the extension didn't work and when I followed the troubleshooting instructions `Apollo GraphQL` was not listed as an option for the output view:
![screen shot 2018-11-07 at 6 07 43 pm](https://user-images.githubusercontent.com/16748392/48166926-2789c400-e2b8-11e8-89c4-7e0fe82bfa9d.png)

**Comment by chanlito** [comment]
Yep, can't find it. Also doesn't seem to work either.

**Comment by tomitrescak** [comment]
Yah, the extension does not work at all, there is no output, all Apollo commands seem not to exist and throw errors. i guess some more final touch ups are needed. Thanks for the effort.

**Comment by tsaiDavid** [comment]
If I'm not mistaken, the cli is also missing the commands that are listed here:

https://www.apollographql.com/docs/tutorial/production.html#publish

`apollo schema:check` and `apollo schema:publish` appear to be unavailable when following through their newly published docs

**Comment by shadaj** [comment]
Hi @jsonunger! Looking at your screenshot, it appears that the extension hasn't been activated. This is usually due to a missing or incorrectly formatted `apollo.config.js` file. For reference, it should look something like this:
```js
module.exports = {
  client: {
    service: "SERVICE_NAME_HERE"
  },
  engine: {
    apiKey: "APOLLO_ENGINE_KEY_HERE"
  }
}
```

**Comment by tomitrescak** [comment]
@shadaj what if I am not using optics but a local schema file or a local endpoint? I tried all possible combinations of the apollo config file and no success:

```
module.exports = {
  client: {
    endpoint: {
      url: 'http://localhost:3000/graphql'
    }
  },
};
```

**Comment by tomitrescak** [comment]
@shadaj awesome! would you be so kind to post an example of working config ? Thanks

**Comment by shadaj** [comment]
@tomitrescak see above ^^ it turned out to have been already fixed, but the docs are a bit out of date so I'm working on fixing that now.

**Comment by tomitrescak** [comment]
Yah, I was too fast. Will wait for the fix. Thanks.

**Comment by shadaj** [comment]
@tomitrescak there actually isn't any fix needed for this (just tested locally with current published version). As long as you put the `service` object inside `client` and put your local endpoint config inside `service`, everything should work.

**Comment by tomitrescak** [comment]
Well, that’s what I have what is shown above. Why it does not start?

**Comment by tomitrescak** [comment]
What I mean is that with the Config format you mentioned it still does not start

**Comment by shadaj** [comment]
Have you reloaded VS Code after updating the config?

**Comment by tomitrescak** [comment]
Yes I did. Do you maybe have a repo which you can share with us, where we can test if problem is in our Config, or extension conflicts? ... I even tried to debug the extension but it is not hitting breakpoints after activation, meaning that the extension refuses to load.

**Comment by tomitrescak** [comment]
[SOLVED] The problem was that I had *.js in my search ignore. Thus VS Code was not finding my config file. You may want to use "fs" directly and not vs code API.

Now I'm fighting #669

**Comment by chanlito** [comment]
What about setting the config in package.json file? Instead of a dedicated
`apollo.config.js`?

**Comment by PaulKujawa** [comment]
Are we talking about activation or installation? As I can't even install the plugin.

**Comment by maarcingebala** [comment]
@shadaj Is using `apiKey` documented anywhere? Eventually, by using [the config from your comment](https://github.com/apollographql/apollo-tooling/issues/664#issuecomment-436874420) I managed to get the plugin working only with the Engine. However, is this the only way to pass the engine key e.g. through env variable? The config file is versioned in our public repo and having keys in there doesn't sound like a good idea.

**Comment by Kresten** [comment]
@maarcingebala 
I am pretty sure that you can do exactly that. You include a `.env` file next to your `apollo.config.js` with `ENGINE_API_KEY=your_key_here`

**Comment by maarcingebala** [comment]
@Kresten I was setting the variable manually in my shell which didn't work, but using `.env` file indeed does 🙂.

**Comment by JakeDawkins** [comment]
I believe everything here has been resolved, so I'm going to close this. Let me know if not :)
