### ISSUE TITLE
apollo: service:push doesn't use apollo.config.js and passing config manually doesn't work

### ISSUE THREAD

**Issue by lnmunhoz** [apollographql/apollo-tooling#835]
I am using `apollo@2.1.8` and I am trying to use the `service:push` command. This command is not using the `apollo.config` even if I try to pass it manually.

When I try to run `apollo service:push --config=apollo.config.js`, I get:
```
✔ Loading Apollo Project
✖ Uploading service to Engine
    → request to http://localhost:4000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4000
```

Even if **my endpoint is defined** in my apollo.config.

My apollo.config.js:
```
module.exports = {
  client: {
    name: "myapp",
    service: "myapp",
      endpoint: {
      url: "http://mydomain.com/graphql",
      headers: {
        "-Hasura-Access-Key": "mykey",
      },
    },
    includes: [
      "./src/components/*.tsx",
      "./src/components/**/*.tsx",
      "./src/client.schema.graphql",
    ],
  },
  engine: {
    apiKey: "service:foo:bar",
  },
}
```

The `apollo client:codegen` command works fine with the exact same config file.
Any ideas?

**Comment by trevor-scheer** [comment]
Hey @lnmunhoz! We've got some fresh docs that I'll point you to for setting up the config, take a look at option 2 here: https://www.apollographql.com/docs/references/apollo-config.html#client-service

I _do_ see an issue with this setup (I've corrected the indentation here):
```javascript
client: {
  name: "myapp",
  service: "myapp",
  endpoint: {
    url: "http://mydomain.com/graphql",
    headers: {
      "-Hasura-Access-Key": "mykey"
    }
  }
}
```

I can't promise this will work since I don't know your config, but if I had to translate this to the correct format, it would look like:
```javascript
client: {
  service: {
    name: "myapp",
    url: "http://mydomain.com/graphql",
    headers: {
      "-Hasura-Access-Key": "mykey"
    }
  }
}
```

**Comment by lnmunhoz** [comment]
Hi @trevor-scheer, so I've tried this other approach and doesn't work as well. The error remains the same, and with this config, the codegen doesn't work anymore.

I will make a repo reproducing this issue if it helps.

**Comment by trevor-scheer** [comment]
Hey @lnmunhoz, sorry for the delay here. Things have been pretty busy, so I'm catching up on some old notifications. If this issue is still ongoing for you, a reproduction would be very helpful for me!

**Comment by lnmunhoz** [comment]
Hey @trevor-scheer, I appreciate your time :)

No, I actually got this working. It was just lack of communication.
I am closing this issue, thank you!

**Comment by jhalborg** [comment]
@lnmunhoz - How did you solve it? I'm seeing a similar issue

**Comment by lnmunhoz** [comment]
@jhalborg I've looked into my commit history and found my config so you can check it out:

```js
module.exports = {
  client: {
    service: {
      name: "envisioning",
      localSchemaFile: "./your/schema/file.graphql"
    },
    includes: [
      "./src/components/**/*.tsx",
      "./src/mutations/**/*.tsx",
      "./src/modals/**/*.tsx",
      "./src/pages/**/*.tsx",
      "./src/fragments.ts",
      "./src/queries.ts",
      "./src/mutations.ts",
      "./src/client.graphql"
    ]
  }
}
```

And the command:
```
apollo codegen:generate --config apollo.config.js --target typescript --outputFlat src/__generated__/gqlTypes.ts,
```

But I don't use `apollo-cli` anymore. I just wanted the type generation and I ended using [graphql-code-generator](https://graphql-code-generator.com) to get the job done.

Hope it helps you, cheers!

**Comment by NWRichmond** [comment]
I also had this issue and figured out what was wrong with my `apollo.config.js` - see #1607 for my solution.

The basic issue here is that if you're connecting to a Hasura GraphQL endpoint, then follow the `server project` convention instead of the `client project` convention (as described by [the docs](https://www.apollographql.com/docs/references/apollo-config/)).
